#!/usr/bin/env bash
client_name=$1

cat <<END
[Interface]
PrivateKey = $(cat secrets/wireguard/$1.pri)
Address = $(jq -r ".roamers.$1.ip_addr" config/wireguard.json)/24
DNS = 8.8.8.8

[Peer]
PublicKey = $(jq -r '.gateway.pubkey' config/wireguard.json)
Endpoint = $(jq -r '.gateway.endpoint' config/wireguard.json):51820
AllowedIPs = 0.0.0.0/0
END
